In [1]:
import random
import pandas as pd
import numpy as np

#### A1: myfirstlist = [] is the faster of the 2 options.

#### A2:

In [2]:
even440 = list(range(4,41,2))
print('even440 : ', even440)

odd540 = list(range(5,40,2))
print('odd540 : ', odd540)

mof5 = list(range(25,101,5))
print('mof5 : ',mof5)

from10to0 = list(range(10,0,-1))
print('from10to0 : ', from10to0)

even440 :  [4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]
odd540 :  [5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]
mof5 :  [25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
from10to0 :  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


#### Sort()

In [3]:
random.seed(4347) #Do not change this seed

x = [random.randint(0,100) for i in range(5)]
print(f'x : {x}')

x.sort()
print(f'x : {x}')

x : [68, 38, 71, 65, 23]
x : [23, 38, 65, 68, 71]


#### Sorted()

In [4]:
sortedx = sorted(x)
print(f'sortedx : {sortedx}')

sortedx : [23, 38, 65, 68, 71]


#### A3: The difference between sort() and sorted() is that sort() will modify the current list by sorting it and sorted() will created a new list that is sorted from the old list

#### A4:

In [5]:
random.seed(4347)
x = [random.randint(0,100) for i in range(25)]
print(f'x: {x}')

x: [68, 38, 71, 65, 23, 26, 18, 23, 18, 15, 16, 6, 69, 3, 81, 47, 68, 80, 93, 21, 66, 13, 37, 98, 49]


#### A5: 2. Start is inclusive end is not

#### A6:

In [6]:
print(f'x reversed: {x[::-1]}')

x reversed: [49, 98, 37, 13, 66, 21, 93, 80, 68, 47, 81, 3, 69, 6, 16, 15, 18, 23, 18, 26, 23, 65, 71, 38, 68]


#### A7: listoflist[3][8] may refer to a list that has 3 indices and each index is a list with 8 indices

#### A8:

In [7]:
data = [('Cameron', 'USA', 29, 50000),
        ('Ricardo', 'Colombia', 34, 100000),
        ('Chase', 'Canada', 31, 120000),
        ('Javier', 'Mexico', 29, 75000),
        ('Jean', 'France', 24, 30000)]
df = pd.DataFrame(data, columns = ['Name','Country','Age','Salary'])
print(df)

      Name   Country  Age  Salary
0  Cameron       USA   29   50000
1  Ricardo  Colombia   34  100000
2    Chase    Canada   31  120000
3   Javier    Mexico   29   75000
4     Jean    France   24   30000


#### A9: I first created sets of the multiples for 8, 9, and 12. I then found the intersection of the 8 and 9 lists to find their common multiples and then intersected that list with the multiples for 12. I then applied the min function to that set to find the lowest common multiple of the three numbers.

In [8]:
multiplesof8 = set(range(8,500,8))
multiplesof9 = set(range(9,500,9))
multiplesof12 = set(range(12,500,12))

multiplesof8and9 = multiplesof8.intersection(multiplesof9)
multiplesof8and9and12 = multiplesof8and9.intersection(multiplesof12)
print('Lowest common multiple of 8, 9, & 12:')
print(min(multiplesof8and9and12))

Lowest common multiple of 8, 9, & 12:
72


#### A10:

In [9]:
a = {'a':1, 'b':2, 'c':3, 'd':4}
print(f'a : {a}')

b = dict(zip(['a','b','c','d'], [1,2,3,4]))
print(f'b : {b}')

c = dict(iter([('a',1),('b',2),('c',3),('d',4)]))
print(f'c : {c}')

d = dict(a=1, b=2, c=3, d=4)
print(f'd : {d}')

a : {'a': 1, 'b': 2, 'c': 3, 'd': 4}
b : {'a': 1, 'b': 2, 'c': 3, 'd': 4}
c : {'a': 1, 'b': 2, 'c': 3, 'd': 4}
d : {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [10]:
def getfrom(dictionary, keys):
  # values = ? #complete your code here
  # check if keys in dict
  if keys in dictionary.keys():
        values = dictionary[keys]
  else:
        values = 999
  return values #should return 999 if key doesn't exist
print(getfrom(dictionary=d, keys='z'))

999


#### A11:

In [11]:
def getfrom(dictionary, keys):
  if keys in dictionary.keys():
      values = dictionary[keys]
  else:
      values = 999
      d['z'] = 999 
  return values #should return 999 if key doesn't exist and should add to dictionary as well

print(getfrom(dictionary=d, keys='z'))

# Now this shouldn't throw error as 'z' is now set to dictionary
print(d['z'])

999
999


#### A12:

In [12]:
# Create two random numpy array of size 10, 10
array1 = np.random.randint(101,size=10) # now we have our list x
array2 = np.random.randint(101,size=10)

print(array1)
print(array2)

#Perform simple matrix addition
add12 = array1 + array2
print(add12)

# Perform matrix multiplication between these two numpy array
mm12 = np.matmul(array1,array2)
print(mm12)

# Perform element wise multiplication between these two array
mmelement = np.multiply(array1,array2)
print(mmelement)

## Calculate mean, standard deviation and variance of mm12
mean = np.mean(mmelement)
print(mean)
std =  np.std(mmelement)
print(std)
var = np.var(mmelement)
print(var)

[ 8  1 66 22 30 51 74 59 18 13]
[95 58 72 26 75 32 91 26 59  5]
[103  59 138  48 105  83 165  85  77  18]
19419
[ 760   58 4752  572 2250 1632 6734 1534 1062   65]
1941.9
2057.6151462311896
4233780.09
